services:
  - type: web
    name: student-marketplace-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SMTP_HOST
        value: smtp-relay.brevo.com
      - key: SMTP_PORT
        value: 587
